import { getContactsForUI } from "./helpers";

const now = Date.now();
const minute = 60 * 1000;
const hour = 60 * minute;
const day = 24 * hour;

const dateFromNow = (offset) => new Date(now - offset);

export let contacts = [
  {
    id: "contact_1",
    firstName: "John",
    lastName: "Smith",
    primaryNumber: "1234567890",
    unread: true,
    lastMsgDate: dateFromNow(30 * 1000),
    email: "john.smith@example.com",
    avatarUrl: "",
    notes: "Notes about John Smith",
    isActive: true,
    createdAt: dateFromNow(1 * day),
  },
  {
    id: "contact_2",
    firstName: "Sarah",
    lastName: "Johnson",
    primaryNumber: "1234567891",
    unread: false,
    lastMsgDate: dateFromNow(30 * minute),
    email: "sarah.johnson@example.com",
    avatarUrl: "",
    notes: "Notes about Sarah Johnson",
    isActive: true,
    createdAt: dateFromNow(2 * day),
  },
  {
    id: "contact_3",
    firstName: "Mike",
    lastName: "Wilson",
    primaryNumber: "1234567892",
    unread: true,
    lastMsgDate: dateFromNow(45 * minute),
    email: "mike.wilson@example.com",
    avatarUrl: "",
    notes: "Notes about Mike Wilson",
    isActive: true,
    createdAt: dateFromNow(3 * day),
  },
  {
    id: "contact_4",
    firstName: "Emily",
    lastName: "Davis",
    primaryNumber: "1234567893",
    unread: false,
    lastMsgDate: dateFromNow(1 * day),
    email: "emily.davis@example.com",
    avatarUrl: "",
    notes: "Notes about Emily Davis",
    isActive: true,
    createdAt: dateFromNow(4 * day),
  },
  {
    id: "contact_5",
    firstName: "David",
    lastName: "Brown",
    primaryNumber: "1234567894",
    unread: false,
    lastMsgDate: dateFromNow(2 * day),
    email: "david.brown@example.com",
    avatarUrl: "",
    notes: "Notes about David Brown",
    isActive: true,
    createdAt: dateFromNow(5 * day),
  },
  {
    id: "contact_6",
    firstName: "Lisa",
    lastName: "Anderson",
    primaryNumber: "1234567895",
    unread: false,
    lastMsgDate: dateFromNow(3 * day),
    email: "lisa.anderson@example.com",
    avatarUrl: "",
    notes: "Notes about Lisa Anderson",
    isActive: true,
    createdAt: dateFromNow(6 * day),
  },
];

export let smsMessages = [
  {
    id: "msg_1_1",
    contactId: "contact_1",
    body: "Hello, how are you?",
    mediaUrl: "",
    mediaType: "",
    isActive: true,
    createdAt: dateFromNow(20 * minute),
    senderId: "user_1",
    direction: "outbound",
    status: "delivered",
  },
  {
    id: "msg_1_2",
    contactId: "contact_1",
    body: "I'm good, thank you!",
    mediaUrl: "",
    mediaType: "",
    isActive: true,
    createdAt: dateFromNow(18 * minute),
    senderId: "contact_1",
    direction: "inbound",
    status: "read",
  },
  {
    id: "msg_1_3",
    contactId: "contact_1",
    body: "Thanks for the update!",
    mediaUrl: "",
    mediaType: "",
    isActive: true,
    createdAt: dateFromNow(5 * minute),
    senderId: "user_1",
    direction: "outbound",
    status: "delivered",
  },
  {
    id: "msg_1_4",
    contactId: "contact_1",
    body: "Can you send me the latest updates?",
    mediaUrl: "",
    mediaType: "",
    isActive: true,
    createdAt: dateFromNow(2 * minute),
    senderId: "contact_1",
    direction: "inbound",
    status: "delivered",
  },
  {
    id: "msg_1_5",
    contactId: "contact_1",
    body: "Also, when is the next meeting scheduled?",
    mediaUrl: "",
    mediaType: "",
    isActive: true,
    createdAt: dateFromNow(30 * 1000),
    senderId: "contact_1",
    direction: "inbound",
    status: "delivered",
  },
  {
    id: "msg_2_1",
    contactId: "contact_2",
    body: "Remember to buy the groceries",
    mediaUrl: "",
    mediaType: "",
    isActive: true,
    createdAt: dateFromNow(40 * minute),
    senderId: "user_1",
    direction: "outbound",
    status: "delivered",
  },
  {
    id: "msg_2_2",
    contactId: "contact_2",
    body: "I'll do it later",
    mediaUrl: "",
    mediaType: "",
    isActive: true,
    createdAt: dateFromNow(38 * minute),
    senderId: "contact_2",
    direction: "inbound",
    status: "read",
  },
  {
    id: "msg_2_3",
    contactId: "contact_2",
    body: "Don't forget to add milk!",
    mediaUrl: "",
    mediaType: "",
    isActive: true,
    createdAt: dateFromNow(34 * minute),
    senderId: "user_1",
    direction: "outbound",
    status: "delivered",
  },
  {
    id: "msg_2_4",
    contactId: "contact_2",
    body: "Can we schedule a meeting for tomorrow?",
    mediaUrl: "",
    mediaType: "",
    isActive: true,
    createdAt: dateFromNow(30 * minute),
    senderId: "contact_2",
    direction: "inbound",
    status: "read",
  },
  {
    id: "msg_3_1",
    contactId: "contact_3",
    body: "Hi, how are you feeling today?",
    mediaUrl: "",
    mediaType: "",
    isActive: true,
    createdAt: dateFromNow(2 * hour),
    senderId: "user_1",
    direction: "outbound",
    status: "delivered",
  },
  {
    id: "msg_3_2",
    contactId: "contact_3",
    body: "I'm feeling better, thank you!",
    mediaUrl: "",
    mediaType: "",
    isActive: true,
    createdAt: dateFromNow(105 * minute),
    senderId: "contact_3",
    direction: "inbound",
    status: "delivered",
  },
  {
    id: "msg_3_3",
    contactId: "contact_3",
    body: "The project is looking great so far!",
    mediaUrl: "",
    mediaType: "",
    isActive: true,
    createdAt: dateFromNow(45 * minute),
    senderId: "contact_3",
    direction: "inbound",
    status: "delivered",
  },
  {
    id: "msg_3_4",
    contactId: "contact_3",
    body: "Here's the image you requested",
    mediaUrl: "https://picsum.photos/400/300",
    mediaType: "image",
    isActive: true,
    createdAt: dateFromNow(40 * minute),
    senderId: "contact_3",
    direction: "inbound",
    status: "delivered",
  },
  {
    id: "msg_4_1",
    contactId: "contact_4",
    body: "I'll send you the files by end of day",
    mediaUrl: "",
    mediaType: "",
    isActive: true,
    createdAt: dateFromNow(1 * day),
    senderId: "contact_4",
    direction: "inbound",
    status: "read",
  },
  {
    id: "msg_5_1",
    contactId: "contact_5",
    body: "Let's catch up next week",
    mediaUrl: "",
    mediaType: "",
    isActive: true,
    createdAt: dateFromNow(2 * day),
    senderId: "contact_5",
    direction: "inbound",
    status: "read",
  },
  {
    id: "msg_6_1",
    contactId: "contact_6",
    body: "The presentation went really well!",
    mediaUrl: "",
    mediaType: "",
    isActive: true,
    createdAt: dateFromNow(3 * day),
    senderId: "contact_6",
    direction: "inbound",
    status: "read",
  },
  {
    id: "msg_2_5",
    contactId: "contact_2",
    body: "Check out this document",
    mediaUrl: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    mediaType: "document",
    isActive: true,
    createdAt: dateFromNow(32 * minute),
    senderId: "user_1",
    direction: "outbound",
    status: "delivered",
  },
];

export const contactsForDemo = getContactsForUI(contacts, smsMessages);